[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[build]
target = "wasm32-unknown-unknown"

[lib]
crate-type = ["cdylib", "rlib"]

[[bench]]
name = "kmeans_benchmark"
harness = false

[dependencies]
getrandom = { version = "0.2.15", features = ["js"] }
packed_simd = { version = "0.3.9", features = ["into_bits"] }
rand = "0.8.5"
rayon = "1.10.0"
wasm-bindgen = "0.2.92"
wasm-bindgen-rayon = "1.2.1"

[dev-dependencies]
criterion = "0.5.1"
