[package]
name = "kmeanspp"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = { version = "0.2.15", features = ["js"] }
rand = "0.8.5"
wasm-bindgen = "0.2.92"

[[bench]]
name = "wasm_benchmarks"
harness = false

[[bench]]
name = "criterion_benchmarks"
harness = false

[dev-dependencies]
criterion = "0.5.1"
statrs = "0.17.1"
wasm-bindgen-test = "0.3.42"
