[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[[bench]]
name = "kmeans_benchmark"
harness = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = { version = "0.2.15", features = ["js"] }
packed_simd = { version = "0.3.9", features = ["into_bits"] }
rand = "0.8.5"
wasm-bindgen = "0.2.92"

[dev-dependencies]
criterion = "0.5.1"
wasm-bindgen-test = "0.3.42"
